#!/usr/bin/env python3
"""Regenerate preview-hero-snow.html + preview/hero-snow-script.js from index.html / script.js.
Preview only (noindex, not linked). Change: hero quick-booking slide → SWITCH ON light-up + full-screen snow → scroll to #booking."""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent

js = (root / 'script.js').read_text()
def jrep(a, b):
    global js
    assert js.count(a) == 1, a
    js = js.replace(a, b)
# 1) slide complete → validate + prefill right away (snow starts now; the ~800ms pause before scrolling lives in hero-snow.js)
jrep("""        goTimer = setTimeout(() => { if (!goLeft && isInView(quick)) goReset(); }, 2500);
      }, 400);""",
     """        goTimer = setTimeout(() => { if (!goLeft && isInView(quick)) goReset(); }, 3500);
      }, 0);   // PREVIEW: was 400ms""")
# 2) the scroll itself goes through the snow overlay (prefill above is unchanged)
jrep("""    $('#booking').scrollIntoView({ behavior: 'smooth', block: 'start' });
    if (!booking.level) msg(""",
     """    const toBooking = () => $('#booking').scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' });
    window.SMHeroSnow ? window.SMHeroSnow.run(toBooking) : toBooking();   // PREVIEW: hero snow
    if (!booking.level) msg(""")
(root / 'preview' / 'hero-snow-script.js').write_text('/* GENERATED by preview/build-hero-preview.py from script.js — preview only */\n' + js)

s = (root / 'index.html').read_text()
def rep(a, b):
    global s
    assert s.count(a) >= 1, a
    s = s.replace(a, b, 1)
rep('<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<meta name="robots" content="noindex, nofollow">')
s = re.sub(r'<title>(.*?)</title>', r'<title>（預覽）\1</title>', s, count=1)
s = re.sub(r'<link rel="canonical"[^>]*>\n?', '', s)
s = re.sub(r'(<link rel="stylesheet" href="style\.css[^"]*">)', r'\1\n<link rel="stylesheet" href="preview/hero-snow.css?v=2">', s, count=1)
n0 = len(s)
s = re.sub(r'<script src="script\.js[^"]*"></script>',
           '<p class="hs-badge" aria-hidden="true">PREVIEW・HERO SNOW</p>\n'
           '<script src="preview/hero-snow.js?v=2"></script>\n<script src="preview/hero-snow-script.js?v=2"></script>', s, count=1)
assert len(s) != n0
(root / 'preview-hero-snow.html').write_text(s)
print('wrote preview-hero-snow.html + preview/hero-snow-script.js')
